version: "3.8"
name: backend_app

services:
  web:
    image: mynode
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: nodeapp
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: manoj444
      POSTGRES_PASSWORD: pgsql
    container_name: database