version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: manoj444
      POSTGRES_PASSWORD: pgsql
  app:
    image: nodeapp
    build:
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
