version: "3.8"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 9000:5432
    environment:
     - POSTGRES_DB=todo
     - POSTGRES_USER=test
     - POSTGRES_PASSWORD=todo12

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080

# connection string : postgresql://test:todo12@db:9000