apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      # should match port exposed in deployment
      targetPort: 8080
      # between 30000 to 32767
      nodePort: 30008