version: "3.8"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=manoj444
      - POSTGRES_PASSWORD=pgsql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
# hostname: db user garne
# database: mydatabase
# password: pgsql
# username: manoj444

# connection string: postgresql://manoj444:pgsq;@localhost:5432/mydatabase