version: "3.8"
services:
  db:
    image: postgres
    restart: always
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 9000:5432
    environment:
      - POSTGRES_DB=ormdb
      - POSTGRES_USER=manoj444
      - POSTGRES_PASSWORD=orm12
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

# connection string: postgresql://<username>:<pw>@<host>:<port>/<database>